<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    
    <PackageReference Include="Microsoft.Azure.Cosmos" />
        <PackageReference Include="Aspire.Hosting.Testing" /><PackageReference Include="coverlet.collector" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Aspire.AppHost\Aspire.AppHost.csproj" />
    <ProjectReference Include="..\..\src\DataAccess.Contracts\DataAccess.Contracts.csproj" />
    <ProjectReference Include="..\..\src\DataAccess\DataAccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>